kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Tuber Api
      - containerPort: 3000
        hostPort: 3000
      # Tuber debug
      - containerPort: 4000
        hostPort: 4000
      # Tuber chat
      - containerPort: 3002
        hostPort: 3002
      # Tuber chat debug
      - containerPort: 4002
        hostPort: 4002
      # Metrics
      - containerPort: 3001
        hostPort: 3001
      # Metrics debug
      - containerPort: 4001
        hostPort: 4001
      # Grafana
      - containerPort: 3100
        hostPort: 3100
      # Vault
      - containerPort: 8200
        hostPort: 8200
      # Postgres
      - containerPort: 5432
        hostPort: 5432
      # Prometheus
      - containerPort: 9090
        hostPort: 9090
      # Tempo (tracing)
      - containerPort: 9411
        hostPort: 9411
      # Redis
      - containerPort: 6379
        hostPort: 6379
