apiVersion: v1
kind: ConfigMap
metadata:
  name: tuber-config
  namespace: tuber-system
data:
  API_HOST: ":3000"
  DEBUG_HOST: ":4000"
  AUTH_AUDIENCE: "543946190000-hh3tm35fnbv2jfl3qmu7q5oqmo9qepfi.apps.googleusercontent.com"
