apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/tuber/
patches:
- path: ./dev-tuber-patch-deploy.yaml
- path: ./dev-tuber-patch-service.yaml
- path: ./dev-tuber-patch-configmap.yaml
images:
- name: service-image
  newName: tuber/service/tuber-api
  newTag: 0.0.1
