apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuber-chat
  namespace: tuber-system
spec:
  selector:
    matchLabels:
      app: tuber-chat
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuber-chat
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
        - name: tuber-chat-container
          env:
            - name: API_HOST
              valueFrom:
                configMapKeyRef:
                  name: tuber-chat-config
                  key: API_HOST
            - name: DEBUG_HOST
              valueFrom:
                configMapKeyRef:
                  name: tuber-chat-config
                  key: DEBUG_HOST
          # resources:
          #   requests:
          #     cpu: "1500m"
          #     memory: 500Mi
          #   limits:
          #     cpu: "1500m"
          #     memory: 500Mi
