apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: tuber-system
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      editable: true
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://kube-prometheus-stack-prometheus:9090
      editable: true
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3101
      editable: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tuber-system
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3100
              name: http-grafana
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: http-grafana
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http-grafana
            timeoutSeconds: 1
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "3100"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "password" # Change this to a secure password
            - name: GF_PROVISIONING_DATASOURCES_PATH
              value: /etc/grafana/provisioning/datasources
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: tuber-system
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - name: http-grafana
      port: 3100
      targetPort: http-grafana
