apiVersion: v1
kind: Service
metadata:
  name: tuber-location-api
  namespace: tuber-system
spec:
  selector:
    app: tuber-location
  type: ClusterIP
  ports:
    - name: loc-api
      port: 3003
      targetPort: 3000
    - name: loc-api-debug
      port: 4003
      targetPort: 4000
