apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/tuber-location
patches:
- path: ./dev-tuber-patch-deploy.yaml
- path: ./dev-tuber-patch-service.yaml
- path: ./dev-tuber-patch-configmap.yaml
images:
- name: service-location-image
  newName: tuber/tuber-location
  newTag: 0.0.2
