repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: kube-prometheus-stack
    namespace: tuber-system
    chart: prometheus-community/kube-prometheus-stack
    version: 52.1.0
    values:
      - kube-prometheus-stack-values.yaml
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: "kubectl"
        args:
          [
            "wait",
            "--for=condition=available",
            "--timeout=600s",
            "deployment/kube-prometheus-stack-operator",
            "-n",
            "{{`{{ .Release.Namespace }}`}}",
          ]
